Update Secrets.yml

diff --git a/.github/workflows/Secrets.yml b/.github/workflows/Secrets.yml
--- a/.github/workflows/Secrets.yml
+++ b/.github/workflows/Secrets.yml
@@ -16,8 +16,8 @@ jobs:
         env:
           SECRET_VALUE: ${{ secrets.MY_SECRET }}
 
-      - name: Intentional Failure
-        run: exit 1 
+      #- name: Intentional Failure
+      #run: exit 1 
 
       - name: Simulate Task Success
         run: echo "This task was successful!"
